### ISSUE TITLE
Parsing is slow

### ISSUE THREAD

**Issue by RupertAvery** [Maximilian-Winter/SrslBytecodeVmAndCodeGenerator#7]
It seems as if parsing is quite slow. I see you built your own parser + lexer, which is really cool, but I noticed that you are throwing/catching Exceptions as part of the parsing logic, and this might be whats causing it to slow down.

I see you have a .g4 grammar and I thought you were using ANTLR4. Any reason you did not use it? Perhaps you didn't want the additional dependency, and you were able to write your own.

Anyway I think parsing performance can be improved a lot.

I haven't built my own parser yet, so I may or may not be able to help in this regard (unless we were to use ANTLR4)

**Comment by Maximilian-Winter** [comment]
I used Antlr4 in the past. I tried to write my own parser, because of the dependency. But I'm planning on using Antlr4 again for the speed and error messages while parsing!
